### PR TITLE
Convert to pure WebExtension

### PR DESCRIPTION
**Pull request by jobisoft**
This converts your extension to a pure WebExtension, to make it work in Thunderbird 115 and later

### CODE REVIEW

**Comment by GTR8000** [comment]
Working great using the files from your fork, thanks!

**Comment by jobisoft** [comment]
> Working great using the files from your fork, thanks!

Nice! If you have time, could you check if this fixes https://github.com/bazuchan/thunderbird-deselect-on-delete/issues/2 as well?

**Comment by GTR8000** [comment]
As far as I can tell, yes, #2 is also fixed. I tested by deleting 2 emails that were right next to each other, as well as 2 emails that had a few emails in between. In both instances, no emails were selected after the deletion. Thanks again! 👍

**Comment by bazuchan** [comment]
> As far as I can tell, yes, #2 is also fixed.

Cool, thanks

**Pull request merged**
